// Generated by CoffeeScript 1.12.7
var ORIGIN, i, len, origin, ref;

ORIGIN = GMAIL_ORIGIN;

if (window.location.ancestorOrigins) {
  ref = window.location.ancestorOrigins;
  for (i = 0, len = ref.length; i < len; i++) {
    origin = ref[i];
    if (origin === GOOGLE_INBOX_ORIGIN) {
      ORIGIN = GOOGLE_INBOX_ORIGIN;
    }
  }
}

document.addEventListener("DOMContentLoaded", function() {
  var chooser;
  chooser = document.createElement("iframe");
  chooser.src = (DROPBOX_BASE + "/chooser?app_key=" + (encodeURIComponent(DROPINS_APP_KEY)) + "&version=3&") + ("origin=" + (encodeURIComponent(ORIGIN)) + "&iframe=true&multiselect=true&folderselect=true");
  document.body.appendChild(chooser);
});
