// Generated by CoffeeScript 1.12.7
var inject_tag;

inject_tag = function() {
  var isInstalledNode;
  isInstalledNode = document.createElement('div');
  isInstalledNode.className = 'dropbox-chrome-ext-is-installed';
  isInstalledNode.setAttribute('data-id', chrome.runtime.id);
  isInstalledNode.setAttribute('data-version', chrome.runtime.getManifest().version);
  isInstalledNode.style.display = "none";
  document.body.appendChild(isInstalledNode);
};

inject_tag();
