/*
* Copyright (C) 2011 Google Inc. All rights reserved.
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions are
* met:
*
*     * Redistributions of source code must retain the above copyright
* notice, this list of conditions and the following disclaimer.
*     * Redistributions in binary form must reproduce the above
* copyright notice, this list of conditions and the following disclaimer
* in the documentation and/or other materials provided with the
* distribution.
*     * Neither the name of Google Inc. nor the names of its
* contributors may be used to endorse or promote products derived from
* this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
* OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
* LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
* DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
* THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
* (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
* OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/**
 * @fileoverview Contains the city to time zone mapping.
 */

/**
 * Clock global name space.
 */
var clockApp = clockApp || {};

/**
 * City to time zone mappings.
 */
clockApp.cityToZoneMapping = {
        'Abidjan': 'africaAbidjan',
        'Accra': 'africaAccra',
        'Adak': 'americaAdak',
        'Addis Ababa': 'africaAddisAbaba',
        'Adelaide': 'australiaAdelaide',
        'Aden': 'asiaAden',
        'Algiers': 'africaAlgiers',
        'Almaty': 'asiaAlmaty',
        'Amman': 'asiaAmman',
        'Amsterdam': 'europeAmsterdam',
        'Anadyr': 'asiaAnadyr',
        'Anchorage': 'americaAnchorage',
        'Andorra': 'europeAndorra',
        'Anguilla': 'americaAnguilla',
        'Antananarivo': 'indianAntananarivo',
        'Antigua': 'americaAntigua',
        'Apia': 'pacificApia',
        'Aqtau': 'asiaAqtau',
        'Aqtobe': 'asiaAqtobe',
        'Araguaina': 'americaAraguaina',
        'Aruba': 'americaAruba',
        'Ashgabat': 'asiaAshgabat',
        'Asmera': 'africaAsmera',
        'Asuncion': 'americaAsuncion',
        'Athens': 'europeAthens',
        'Auckland': 'pacificAuckland',
        'Azores': 'atlanticAzores',
        'Baghdad': 'asiaBaghdad',
        'Bahia': 'americaBahia',
        'Bahrain': 'asiaBahrain',
        'Baku': 'asiaBaku',
        'Bamako': 'africaBamako',
        'Bangkok': 'asiaBangkok',
        'Bangui': 'africaBangui',
        'Banjul': 'africaBanjul',
        'Barbados': 'americaBarbados',
        'Beirut': 'asiaBeirut',
        'Belem': 'americaBelem',
        'Belgrade': 'europeBelgrade',
        'Belize': 'americaBelize',
        'Berlin': 'europeBerlin',
        'Bermuda': 'atlanticBermuda',
        'Bishkek': 'asiaBishkek',
        'Bissau': 'africaBissau',
        'Blanc-Sablon': 'americaBlancSablon',
        'Blantyre': 'africaBlantyre',
        'Boa Vista': 'americaBoaVista',
        'Bogota': 'americaBogota',
        'Boise': 'americaBoise',
        'Bratislava': 'europeBratislava',
        'Brazzaville': 'africaBrazzaville',
        'Brisbane': 'australiaBrisbane',
        'Broken Hill': 'australiaBrokenHill',
        'Brunei': 'asiaBrunei',
        'Brussels': 'europeBrussels',
        'Bucharest': 'europeBucharest',
        'Budapest': 'europeBudapest',
        'Buenos Aires': 'americaBuenosAires',
        'Bujumbura': 'africaBujumbura',
        'Cairo': 'africaCairo',
        'Calcutta': 'asiaCalcutta',
        'Cambridge Bay': 'americaCambridgeBay',
        'Campo Grande': 'americaCampoGrande',
        'Canary': 'atlanticCanary',
        'Cancun': 'americaCancun',
        'Cape Verde': 'atlanticCapeVerde',
        'Caracas': 'americaCaracas',
        'Casablanca': 'africaCasablanca',
        'Casey': 'antarcticaCasey',
        'Catamarca': 'americaCatamarca',
        'Cayenne': 'americaCayenne',
        'Cayman': 'americaCayman',
        'Center': 'americaNorthDakotaCenter',
        'Ceuta': 'africaCeuta',
        'Chagos': 'indianChagos',
        'Chatham': 'pacificChatham',
        'Chicago': 'americaChicago',
        'Chihuahua': 'americaChihuahua',
        'Chisinau': 'europeChisinau',
        'Choibalsan': 'asiaChoibalsan',
        'Chongqing': 'asiaChongqing',
        'Christmas': 'indianChristmas',
        'Cocos': 'indianCocos',
        'Colombo': 'asiaColombo',
        'Comoro': 'indianComoro',
        'Conakry': 'africaConakry',
        'Copenhagen': 'europeCopenhagen',
        'Coral Harbour': 'americaCoralHarbour',
        'Cordoba': 'americaCordoba',
        'Costa Rica': 'americaCostaRica',
        'Cuiaba': 'americaCuiaba',
        'Curacao': 'americaCuracao',
        'Currie': 'australiaCurrie',
        'Dakar': 'africaDakar',
        'Damascus': 'asiaDamascus',
        'Danmarkshavn': 'americaDanmarkshavn',
        'Dar es Salaam': 'africaDaresSalaam',
        'Darwin': 'australiaDarwin',
        'Davis': 'antarcticaDavis',
        'Dawson Creek': 'americaDawsonCreek',
        'Dawson': 'americaDawson',
        'Denver': 'americaDenver',
        'Detroit': 'americaDetroit',
        'Dhaka': 'asiaDhaka',
        'Dili': 'asiaDili',
        'Djibouti': 'africaDjibouti',
        'Dominica': 'americaDominica',
        'Douala': 'africaDouala',
        'Dubai': 'asiaDubai',
        'Dublin': 'europeDublin',
        'DumontDUrville': 'antarcticaDumontDUrville',
        'Dushanbe': 'asiaDushanbe',
        'Easter': 'pacificEaster',
        'Edmonton': 'americaEdmonton',
        'Efate': 'pacificEfate',
        'Eirunepe': 'americaEirunepe',
        'El Aaiun': 'africaElAaiun',
        'El Salvador': 'americaElSalvador',
        'Enderbury': 'pacificEnderbury',
        'Eucla': 'australiaEucla',
        'Faeroe': 'atlanticFaeroe',
        'Fakaofo': 'pacificFakaofo',
        'Fiji': 'pacificFiji',
        'Fortaleza': 'americaFortaleza',
        'Freetown': 'africaFreetown',
        'Funafuti': 'pacificFunafuti',
        'Gaborone': 'africaGaborone',
        'Galapagos': 'pacificGalapagos',
        'Gambier': 'pacificGambier',
        'Gaza': 'asiaGaza',
        'Gibraltar': 'europeGibraltar',
        'Glace Bay': 'americaGlaceBay',
        'Godthab': 'americaGodthab',
        'Goose Bay': 'americaGooseBay',
        'Grand Turk': 'americaGrandTurk',
        'Grenada': 'americaGrenada',
        'Guadalcanal': 'pacificGuadalcanal',
        'Guadeloupe': 'americaGuadeloupe',
        'Guam': 'pacificGuam',
        'Guatemala': 'americaGuatemala',
        'Guayaquil': 'americaGuayaquil',
        'Guernsey': 'europeGuernsey',
        'Guyana': 'americaGuyana',
        'Halifax': 'americaHalifax',
        'Harare': 'africaHarare',
        'Harbin': 'asiaHarbin',
        'Havana': 'americaHavana',
        'Helsinki': 'europeHelsinki',
        'Hermosillo': 'americaHermosillo',
        'Hobart': 'australiaHobart',
        'Hong Kong': 'asiaHongKong',
        'Honolulu': 'pacificHonolulu',
        'Hovd': 'asiaHovd',
        'Indianapolis': 'americaIndianapolis',
        'Inuvik': 'americaInuvik',
        'Iqaluit': 'americaIqaluit',
        'Irkutsk': 'asiaIrkutsk',
        'Isle of Man': 'europeIsleofMan',
        'Istanbul': 'europeIstanbul',
        'Jakarta': 'asiaJakarta',
        'Jamaica': 'americaJamaica',
        'Jayapura': 'asiaJayapura',
        'Jersey': 'europeJersey',
        'Jerusalem': 'asiaJerusalem',
        'Johannesburg': 'africaJohannesburg',
        'Johnston': 'pacificJohnston',
        'Jujuy': 'americaJujuy',
        'Juneau': 'americaJuneau',
        'Kabul': 'asiaKabul',
        'Kaliningrad': 'europeKaliningrad',
        'Kamchatka': 'asiaKamchatka',
        'Kampala': 'africaKampala',
        'Karachi': 'asiaKarachi',
        'Kashgar': 'asiaKashgar',
        'Katmandu': 'asiaKatmandu',
        'Kerguelen': 'indianKerguelen',
        'Khartoum': 'africaKhartoum',
        'Kiev': 'europeKiev',
        'Kigali': 'africaKigali',
        'Kinshasa': 'africaKinshasa',
        'Kiritimati': 'pacificKiritimati',
        'Knox': 'americaIndianaKnox',
        'Kosrae': 'pacificKosrae',
        'Krasnoyarsk': 'asiaKrasnoyarsk',
        'Kuala Lumpur': 'asiaKualaLumpur',
        'Kuching': 'asiaKuching',
        'Kuwait': 'asiaKuwait',
        'Kwajalein': 'pacificKwajalein',
        'La Paz': 'americaLaPaz',
        'La Rioja': 'americaArgentinaLaRioja',
        'Lagos': 'africaLagos',
        'Libreville': 'africaLibreville',
        'Lima': 'americaLima',
        'Lindeman': 'australiaLindeman',
        'Lisbon': 'europeLisbon',
        'Ljubljana': 'europeLjubljana',
        'Lome': 'africaLome',
        'London': 'europeLondon',
        'Longyearbyen': 'arcticLongyearbyen',
        'Lord Howe': 'australiaLordHowe',
        'Los Angeles': 'americaLosAngeles',
        'Louisville': 'americaLouisville',
        'Luanda': 'africaLuanda',
        'Lubumbashi': 'africaLubumbashi',
        'Lusaka': 'africaLusaka',
        'Luxembourg': 'europeLuxembourg',
        'Macau': 'asiaMacau',
        'Maceio': 'americaMaceio',
        'Madeira': 'atlanticMadeira',
        'Madrid': 'europeMadrid',
        'Magadan': 'asiaMagadan',
        'Mahe': 'indianMahe',
        'Majuro': 'pacificMajuro',
        'Makassar': 'asiaMakassar',
        'Malabo': 'africaMalabo',
        'Maldives': 'indianMaldives',
        'Malta': 'europeMalta',
        'Managua': 'americaManagua',
        'Manaus': 'americaManaus',
        'Manila': 'asiaManila',
        'Maputo': 'africaMaputo',
        'Marengo': 'americaIndianaMarengo',
        'Mariehamn': 'europeMariehamn',
        'Marigot': 'americaMarigot',
        'Marquesas': 'pacificMarquesas',
        'Martinique': 'americaMartinique',
        'Maseru': 'africaMaseru',
        'Mauritius': 'indianMauritius',
        'Mawson': 'antarcticaMawson',
        'Mayotte': 'indianMayotte',
        'Mazatlan': 'americaMazatlan',
        'Mbabane': 'africaMbabane',
        'McMurdo': 'antarcticaMcMurdo',
        'Melbourne': 'australiaMelbourne',
        'Mendoza': 'americaMendoza',
        'Menominee': 'americaMenominee',
        'Merida': 'americaMerida',
        'Mexico City': 'americaMexicoCity',
        'Midway': 'pacificMidway',
        'Minsk': 'europeMinsk',
        'Miquelon': 'americaMiquelon',
        'Mogadishu': 'africaMogadishu',
        'Monaco': 'europeMonaco',
        'Moncton': 'americaMoncton',
        'Monrovia': 'africaMonrovia',
        'Monterrey': 'americaMonterrey',
        'Montevideo': 'americaMontevideo',
        'Monticello': 'americaKentuckyMonticello',
        'Montreal': 'americaMontreal',
        'Montserrat': 'americaMontserrat',
        'Moscow': 'europeMoscow',
        'Muscat': 'asiaMuscat',
        'Nairobi': 'africaNairobi',
        'Nassau': 'americaNassau',
        'Nauru': 'pacificNauru',
        'Ndjamena': 'africaNdjamena',
        'New Salem': 'americaNorthDakotaNewSalem',
        'New York': 'americaNewYork',
        'Niamey': 'africaNiamey',
        'Nicosia': 'asiaNicosia',
        'Nipigon': 'americaNipigon',
        'Niue': 'pacificNiue',
        'Nome': 'americaNome',
        'Norfolk': 'pacificNorfolk',
        'Noronha': 'americaNoronha',
        'Nouakchott': 'africaNouakchott',
        'Noumea': 'pacificNoumea',
        'Novosibirsk': 'asiaNovosibirsk',
        'Omsk': 'asiaOmsk',
        'Oral': 'asiaOral',
        'Oslo': 'europeOslo',
        'Ouagadougou': 'africaOuagadougou',
        'Pago Pago': 'pacificPagoPago',
        'Palau': 'pacificPalau',
        'Palmer': 'antarcticaPalmer',
        'Panama': 'americaPanama',
        'Pangnirtung': 'americaPangnirtung',
        'Paramaribo': 'americaParamaribo',
        'Paris': 'europeParis',
        'Perth': 'australiaPerth',
        'Petersburg': 'americaIndianaPetersburg',
        'Phnom Penh': 'asiaPhnomPenh',
        'Phoenix': 'americaPhoenix',
        'Pitcairn': 'pacificPitcairn',
        'Podgorica': 'europePodgorica',
        'Ponape': 'pacificPonape',
        'Pontianak': 'asiaPontianak',
        'Port Moresby': 'pacificPortMoresby',
        'Port of Spain': 'americaPortofSpain',
        'Port-au-Prince': 'americaPortauPrince',
        'Porto Velho': 'americaPortoVelho',
        'Porto-Novo': 'africaPortoNovo',
        'Prague': 'europePrague',
        'Puerto Rico': 'americaPuertoRico',
        'Pyongyang': 'asiaPyongyang',
        'Qatar': 'asiaQatar',
        'Qyzylorda': 'asiaQyzylorda',
        'Rainy River': 'americaRainyRiver',
        'Rangoon': 'asiaRangoon',
        'Rankin Inlet': 'americaRankinInlet',
        'Rarotonga': 'pacificRarotonga',
        'Recife': 'americaRecife',
        'Regina': 'americaRegina',
        'Resolute': 'americaResolute',
        'Reunion': 'indianReunion',
        'Reykjavik': 'atlanticReykjavik',
        'Riga': 'europeRiga',
        'Rio Branco': 'americaRioBranco',
        'Rio Gallegos': 'americaArgentinaRioGallegos',
        'Riyadh': 'asiaRiyadh',
        'Rome': 'europeRome',
        'Rothera': 'antarcticaRothera',
        'Saigon': 'asiaSaigon',
        'Saipan': 'pacificSaipan',
        'Sakhalin': 'asiaSakhalin',
        'Samara': 'europeSamara',
        'Samarkand': 'asiaSamarkand',
        'San Juan': 'americaArgentinaSanJuan',
        'San Marino': 'europeSanMarino',
        'Santiago': 'americaSantiago',
        'Santo Domingo': 'americaSantoDomingo',
        'Sao Paulo': 'americaSaoPaulo',
        'Sao Tome': 'africaSaoTome',
        'Sarajevo': 'europeSarajevo',
        'Scoresbysund': 'americaScoresbysund',
        'Seoul': 'asiaSeoul',
        'Shanghai': 'asiaShanghai',
        'Shiprock': 'americaShiprock',
        'Simferopol': 'europeSimferopol',
        'Singapore': 'asiaSingapore',
        'Skopje': 'europeSkopje',
        'Sofia': 'europeSofia',
        'South Georgia': 'atlanticSouthGeorgia',
        'St Barthelemy': 'americaStBarthelemy',
        'St Helena': 'atlanticStHelena',
        'St Johns': 'americaStJohns',
        'St Kitts': 'americaStKitts',
        'St Lucia': 'americaStLucia',
        'St Thomas': 'americaStThomas',
        'St Vincent': 'americaStVincent',
        'Stanley': 'atlanticStanley',
        'Stockholm': 'europeStockholm',
        'Swift Current': 'americaSwiftCurrent',
        'Sydney': 'australiaSydney',
        'Syowa': 'antarcticaSyowa',
        'Tahiti': 'pacificTahiti',
        'Taipei': 'asiaTaipei',
        'Tallinn': 'europeTallinn',
        'Tarawa': 'pacificTarawa',
        'Tashkent': 'asiaTashkent',
        'Tbilisi': 'asiaTbilisi',
        'Tegucigalpa': 'americaTegucigalpa',
        'Tehran': 'asiaTehran',
        'Tell City': 'americaIndianaTellCity',
        'Thimphu': 'asiaThimphu',
        'Thule': 'americaThule',
        'Thunder Bay': 'americaThunderBay',
        'Tijuana': 'americaTijuana',
        'Tirane': 'europeTirane',
        'Tokyo': 'asiaTokyo',
        'Tongatapu': 'pacificTongatapu',
        'Toronto': 'americaToronto',
        'Tortola': 'americaTortola',
        'Tripoli': 'africaTripoli',
        'Truk': 'pacificTruk',
        'Tucuman': 'americaArgentinaTucuman',
        'Tunis': 'africaTunis',
        'Ulaanbaatar': 'asiaUlaanbaatar',
        'Urumqi': 'asiaUrumqi',
        'Ushuaia': 'americaArgentinaUshuaia',
        'Uzhgorod': 'europeUzhgorod',
        'Vaduz': 'europeVaduz',
        'Vancouver': 'americaVancouver',
        'Vatican': 'europeVatican',
        'Vevay': 'americaIndianaVevay',
        'Vienna': 'europeVienna',
        'Vientiane': 'asiaVientiane',
        'Vilnius': 'europeVilnius',
        'Vincennes': 'americaIndianaVincennes',
        'Vladivostok': 'asiaVladivostok',
        'Volgograd': 'europeVolgograd',
        'Vostok': 'antarcticaVostok',
        'Wake': 'pacificWake',
        'Wallis': 'pacificWallis',
        'Warsaw': 'europeWarsaw',
        'Whitehorse': 'americaWhitehorse',
        'Winamac': 'americaIndianaWinamac',
        'Windhoek': 'africaWindhoek',
        'Winnipeg': 'americaWinnipeg',
        'Yakutat': 'americaYakutat',
        'Yakutsk': 'asiaYakutsk',
        'Yekaterinburg': 'asiaYekaterinburg',
        'Yellowknife': 'americaYellowknife',
        'Yerevan': 'asiaYerevan',
        'Zagreb': 'europeZagreb',
        'Zaporozhye': 'europeZaporozhye',
        'Zurich': 'europeZurich'
};
