/*
 RequireJS domReady 2.0.1 Copyright (c) 2010-2012, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/requirejs/domReady for details
 MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors */
define("third_party/domready/domReady",[],function(){function d(){if(!f){f=!0;r&&clearInterval(r);var a=l;if(f&&a.length){l=[];var b;for(b=0;b<a.length;b+=1)a[b](h)}}}function c(a){f?a(h):l.push(a);return c}var b,a,r,e="undefined"!==typeof window&&window.document,f=!e,h=e?document:null,l=[];if(e){if(document.addEventListener)document.addEventListener("DOMContentLoaded",d,!1),window.addEventListener("load",d,!1);else if(window.attachEvent){window.attachEvent("onload",d);a=document.createElement("div");
try{b=null===window.frameElement}catch(k){}a.doScroll&&b&&window.external&&(r=setInterval(function(){try{a.doScroll(),d()}catch(b){}},30))}"complete"===document.readyState&&d()}c.version="2.0.1";c.load=function(a,b,d,e){e.isBuild?d(null):c(d)};return c});
define("qowtRoot/utils/typeUtils",[],function(){function d(a,c,d){if(d.types.every(function(a){var c=b[a];if(!c)throw Error("Bad config to checkArgTypes: unknown type: "+a);return!c(d.value)})){var f=1===d.types.length?d.types[0]:"["+d.types.join(",")+"]";throw Error("Argument "+c+" passed to function "+a+" was supposed to be of type "+f+" but had value "+d.value);}}var c={checkArgTypes:function(a,b){for(var c in b){var f={value:b[c][0],types:b[c].slice(1)};d(a,c,f)}},isObject:function(a){return"object"===
typeof a&&null!==a},isPromise:function(a){return a instanceof Promise},isPromiseLike:function(a){return!(!a||!c.isFunction(a.then))},isList:function(a){return"[object Array]"===Object.prototype.toString.call(a)},isNumber:function(a){return"number"===typeof a&&!isNaN(a)},isInteger:function(a){return"number"===typeof a&&parseInt(a,10)===a},isFunction:function(a){return"function"===typeof a},isString:function(a){return"[object String]"===Object.prototype.toString.call(a)},isRegex:function(a){return"[object RegExp]"===
Object.prototype.toString.call(a)},isNode:function(a){return a instanceof Node},isNull:function(a){return null===a},isUndefined:function(a){return void 0===a},isBoolean:function(a){return"boolean"===typeof a},getType:function(a){var c;Object.keys(b).forEach(function(d){b[d](a)&&(c=d)});return c},isArgumentsObjectOrList:function(a){return a instanceof Object&&a.hasOwnProperty("length")},extend:function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])},createNewType:function(a){var c=function(){},
d={isOfType:function(a){return void 0!==a&&null!==a&&a.constructor===c},markAsType:function(a){Object.defineProperty(a,"constructor",{value:c,configurable:!1,writable:!1,enumerable:!1});return a}};if(a){if(b[a])throw Error("Already registered type "+a);b[a]=d.isOfType}return d}},b={string:c.isString,object:c.isObject,promise:c.isPromise,promiseLike:c.isPromiseLike,node:c.isNode,regex:c.isRegex,"function":c.isFunction,number:c.isNumber,list:c.isList,boolean:c.isBoolean,"null":c.isNull,undefined:c.isUndefined};
return c});(function(){var d={},c=window.sessionStorage.getItem("featureOverrides");c&&(d=JSON.parse(c));d.isRelease=!0;d.edit=!1;window.sessionStorage.setItem("featureOverrides",JSON.stringify(d));window.localStorage.removeItem("testsToInclude");window.localStorage.removeItem("builtInTests")})();define("configs/releaseFeatures",function(){});
(function(){var d={},c=window.sessionStorage.getItem("featureOverrides");c&&(d=JSON.parse(c));d.save=!!(window.chrome&&window.chrome.fileSystem&&window.chrome.fileSystem.chooseEntry);window.sessionStorage.setItem("featureOverrides",JSON.stringify(d))})();define("configs/chromeFeatures",function(){});define("qowtRoot/features/pack",[],function(){return{edit:!0,save:!1,pointEdit:!1,hats:!0}});
define("qowtRoot/features/utils",["qowtRoot/features/pack"],function(d){var c={isEnabled:function(a){a=d[a];return void 0===a?!1:a},enable:function(a){d[a]=!0},disable:function(a){d[a]=!1},setOverrides:function(a){for(var b in a)a.hasOwnProperty(b)&&(d[b]=a[b])},isDebug:function(){return void 0!==b?b:!c.isEnabled("isRelease")},setDebugOverride:function(a){b=a},clearDebugOverride:function(){b=void 0}},b;return c});
(function(d){d("qowtRoot/third_party/when/lib/timer",["require"],function(c){return{set:setTimeout,clear:clearTimeout}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
(function(d){d("qowtRoot/third_party/when/lib/timed",[],function(){return function(c,b,a){a.prototype.delay=function(a){var b=this;return new this.constructor(function(d,h,l){b.then(function(b){c(function(){d(b)},a)},h,l)})};a.prototype.timeout=function(a,d){var f=this,h=1<arguments.length;return new this.constructor(function(l,k,t){var n=c(function(){k(h?d:Error("timed out after "+a+"ms"))},a);f.then(function(a){b(n);l(a)},function(a){b(n);k(a)},t)})};return a}})})("function"===typeof define&&define.amd?
define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/array",[],function(){return function(c){var b=Array.prototype.map,a=Array.prototype.reduce,d=Array.prototype.reduceRight,e=Array.prototype.forEach,f=c.resolve,h=c.all;c.any=function(a){return new c(function(b,c){function d(a){h.push(a);0===--r&&c(h)}var r=0,h=[];e.call(a,function(a){++r;f(a).then(b,d)});0===r&&b()})};c.some=function(a,b){return new c(function(c,d,r){function h(a){0<g&&(--g,p.push(a),0===g&&c(p))}function u(a){0<q&&(--q,v.push(a),0===q&&
d(v))}var g=0,q,p=[],v=[];e.call(a,function(a){++g;f(a).then(h,u,r)});b=Math.max(b,0);q=g-b+1;g=Math.min(b,g);0===g&&c(p)})};c.settle=function(a){return h(b.call(a,function(a){function b(){return a.inspect()}a=f(a);return a.then(b,b)}))};c.map=function(a,c,d){return h(b.call(a,function(a){return f(a).then(c,d)}))};c.reduce=function(b,c){function d(a,b,e){return f(a).then(function(a){return f(b).then(function(b){return c(a,b,e)})})}return 2<arguments.length?a.call(b,d,arguments[2]):a.call(b,d)};c.reduceRight=
function(a,b){function c(a,d,e){return f(a).then(function(a){return f(d).then(function(c){return b(a,c,e)})})}return 2<arguments.length?d.call(a,c,arguments[2]):d.call(a,c)};c.prototype.spread=function(a){return this.then(h).then(function(b){return a.apply(void 0,b)})};return c}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/fatal",["require","./timer"],function(c){var b=c("./timer").set;return function(a){b(function(){throw a;},0)}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
(function(d){d("qowtRoot/third_party/when/lib/flow",["require","./fatal"],function(c){function b(){throw new TypeError("catch predicate must be a function");}function a(a,b){return function(){a.call(this);return b}}function d(){}var e=c("./fatal");return function(c){function h(a,b){return function(c){return(b===Error||null!=b&&b.prototype instanceof Error?c instanceof b:b(c))?a.call(this,c):k(c)}}var l=c.resolve,k=c.reject,t=c.prototype["catch"];c.prototype.done=function(a,b){var c=this._handler;
c.when(this._maybeFatal,d,this,c.receiver,a,b)};c.prototype._maybeFatal=function(a){if(Object(a)===a)l(a)["catch"](this._fatal)};c.prototype._fatal=e;c.prototype["catch"]=c.prototype.otherwise=function(a){return 1===arguments.length?t.call(this,a):"function"!==typeof a?this.ensure(b):t.call(this,h(arguments[1],a))};c.prototype["finally"]=c.prototype.ensure=function(b){if("function"!==typeof b)return this;b=a(b,this);return this.then(b,b)};c.prototype["else"]=c.prototype.orElse=function(a){return this.then(void 0,
function(){return a})};c.prototype.yield=function(a){return this.then(function(){return a})};c.prototype.tap=function(a){return this.then(a).yield(this)};return c}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});(function(d){d("qowtRoot/third_party/when/lib/inspect",[],function(){return function(c){c.prototype.inspect=function(){return this._handler.inspect()};return c}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/iterate",[],function(){return function(c){function b(a,c,h,l){function k(k){return d(h(k)).then(function(){return b(a,c,h,a(k))})}return d(l).then(function(a){return d(c(a)).then(function(b){return b?a:k(a)})})}function a(b,c,h,l){function k(k,l){return d(h(k)).then(function(){return a(b,c,h,l)})}return d(l).then(function(a){return d(c(a)).then(function(c){return c?a:d(b(a)).spread(k)})})}var d=c.resolve;c.iterate=b;c.unfold=a;return c}})})("function"===
typeof define&&define.amd?define:function(d){module.exports=d()});(function(d){d("qowtRoot/third_party/when/lib/progress",[],function(){return function(c){c.prototype.progress=function(b){return this.then(void 0,void 0,b)};return c}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/with",[],function(){return function(c){c.prototype["with"]=c.prototype.withThis=c.prototype._bindContext;return c}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/makePromise",[],function(){return function(c){function b(b){var c=this;this._handler=new n;a(b,function(a){c._handler.resolve(a)},function(a){c._handler.reject(a)},function(a){c._handler.notify(a)})}function a(a,b,c,d){try{a(b,c,d)}catch(e){c(e)}}function d(a){return new e(new x(new q(a)))}function e(a){this._handler=a}function f(a,c){if(a instanceof b){var d=a._handler.join();return c===d?new q(new TypeError("Promise cycle")):d}return C(a)?l(a):new g(a)}
function h(a){return a instanceof b?a._handler.join():l(a)}function l(a){try{var b=a.then;return"function"===typeof b?new u(b,a):new g(a)}catch(c){return new q(c)}}function k(){}function t(a){this.handler=a;if(this._isMonitored()){var b=this._env.promiseMonitor.captureStack();this.trace=a._addTrace(b)}}function n(a){this.consumers=[];this.receiver=a;this.handler=void 0;this.resolved=!1;this._isMonitored()&&(this.trace=this._env.promiseMonitor.captureStack())}function x(a){t.call(this,a)}function z(a,
b){t.call(this,a);this.receiver=b}function u(a,b){n.call(this);this.assimilated=!1;this.untrustedThen=a;this.thenable=b}function g(a){this.value=a}function q(a){this.value=a;this.observed=!1;this._isMonitored()&&(this.key=this._env.promiseMonitor.startTrace(a))}function p(){return{state:"pending"}}function v(a,b,c,d,e,m,r,h){this.a=a;this.b=b;this.c=c;this.d=d;this.e=e;this.f=m;this.g=r;this.handler=h}function m(a,b){this.q=a;this.value=b}function C(a){return("object"===typeof a||"function"===typeof a)&&
null!==a}function D(a,b,c){try{return a.call(c,b)}catch(e){return d(e)}}function w(){}var B,A=c.scheduler,y=Object.create||function(a){function b(){}b.prototype=a;return new b};b.resolve=function(a){return a instanceof b?a:new e(new x(f(a)))};b.reject=d;b.never=function(){return B};b._defer=function(){return new e(new n)};b.prototype.then=function(a,b,c){var d=this._handler,m=new n(d.receiver);d.when(m.resolve,m.notify,m,d.receiver,a,b,c);return new e(m)};b.prototype["catch"]=b.prototype.otherwise=
function(a){return this.then(void 0,a)};b.prototype._bindContext=function(a){return new e(new z(this._handler,a))};b.all=function(a){function b(a,c,d,e){d.when(w,w,void 0,a,function(a){c[e]=a;0===--m&&this.resolve(c)},a.reject,a.notify)}var c=new n,d=a.length>>>0,m=d,r=[],f,g;for(f=0;f<d;++f)f in a?(g=a[f],C(g)?b(c,r,h(g),f):(r[f]=g,--m)):--m;0===m&&c.resolve(r);return new e(c)};b.race=function(a){if(Object(a)===a&&0===a.length)return B;for(var b=new n,c=0;c<a.length;++c)f(a[c]).when(w,w,void 0,b,
b.resolve,b.reject);return new e(b)};e.prototype=y(b.prototype);k.prototype.inspect=p;k.prototype.when=w;k.prototype.resolve=w;k.prototype.reject=w;k.prototype.notify=w;k.prototype.join=function(){return this};k.prototype._env=c.monitor||b;k.prototype._addTrace=w;k.prototype._isMonitored=function(){return"undefined"!==typeof this._env.promiseMonitor};t.prototype=y(k.prototype);t.prototype.join=function(){return this.handler.join()};t.prototype.inspect=function(){return this.handler.inspect()};t.prototype._addTrace=
function(a){return this.handler._addTrace(a)};n.prototype=y(k.prototype);n.prototype.inspect=function(){return this.resolved?this.handler.join().inspect():p()};n.prototype.resolve=function(a){this._join(f(a,this))};n.prototype.reject=function(a){this._join(new q(a))};n.prototype.join=function(){return this.resolved?this.handler.join():this};n.prototype.run=function(){var a=this.consumers,b=this.handler=this.handler.join();this.consumers=void 0;for(var c=0;c<a.length;c+=7)b.when(a[c],a[c+1],a[c+2],
a[c+3],a[c+4],a[c+5],a[c+6])};n.prototype._join=function(a){this.resolved||(this.resolved=!0,this.handler=a,A.enqueue(this),this._isMonitored()&&(this.trace=a._addTrace(this.trace)))};n.prototype.when=function(a,b,c,d,e,m,f){this.resolved?A.enqueue(new v(a,b,c,d,e,m,f,this.handler.join())):this.consumers.push(a,b,c,d,e,m,f)};n.prototype.notify=function(a){this.resolved||A.enqueue(new m(this.consumers,a))};n.prototype._addTrace=function(a){return this.resolved?this.handler._addTrace(a):a};x.prototype=
y(t.prototype);x.prototype.when=function(a,b,c,d,e,m,f){A.enqueue(new v(a,b,c,d,e,m,f,this.join()))};z.prototype=y(t.prototype);z.prototype.when=function(a,b,c,d,e,m,f){void 0!==this.receiver&&(d=this.receiver);this.join().when(a,b,c,d,e,m,f)};u.prototype=y(n.prototype);u.prototype.when=function(a,b,c,d,e,m,f){this.assimilated||(this.assimilated=!0,this._assimilate());n.prototype.when.call(this,a,b,c,d,e,m,f)};u.prototype._assimilate=function(){var a=this;this._try(this.untrustedThen,this.thenable,
function(b){a.resolve(b)},function(b){a.reject(b)},function(b){a.notify(b)})};u.prototype._try=function(a,b,c,d,e){try{a.call(b,c,d,e)}catch(m){d(m)}};g.prototype=y(k.prototype);g.prototype.inspect=function(){return{state:"fulfilled",value:this.value}};g.prototype.when=function(a,b,c,d,e){b="function"===typeof e?D(e,this.value,d):this.value;a.call(c,b)};q.prototype=y(k.prototype);q.prototype.inspect=function(){return{state:"rejected",reason:this.value}};q.prototype.when=function(a,b,c,e,m,f){this._isMonitored()&&
!this.observed&&this._env.promiseMonitor.removeTrace(this.key);this.observed=!0;b="function"===typeof f?D(f,this.value,e):d(this.value);a.call(c,b)};q.prototype._addTrace=function(a){this.observed||this._env.promiseMonitor.updateTrace(this.key,a)};B=new e(new k);v.prototype.run=function(){this.handler.when(this.a,this.b,this.c,this.d,this.e,this.f,this.g)};m.prototype.run=function(){for(var a=this.q,b=1;b<a.length;b+=7)this._notify(a[b],a[b+1],a[b+2],a[b+5])};m.prototype._notify=function(a,b,c,d){var e;
if("function"===typeof d)try{e=d.call(c,this.value)}catch(m){e=m}else e=this.value;a.call(b,e)};return b}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/Queue",[],function(){function c(b){this.head=this.tail=this.length=0;this.buffer=Array(1<<b)}c.prototype.push=function(b){this.length===this.buffer.length&&this._ensureCapacity(2*this.length);this.buffer[this.tail]=b;this.tail=this.tail+1&this.buffer.length-1;++this.length;return this.length};c.prototype.shift=function(){var b=this.buffer[this.head];this.buffer[this.head]=void 0;this.head=this.head+1&this.buffer.length-1;--this.length;return b};c.prototype._ensureCapacity=
function(b){var a=this.head,c=this.buffer,d=Array(b),f=0,h;if(0===a)for(h=this.length;f<h;++f)d[f]=c[f];else{b=c.length;for(h=this.tail;a<b;++f,++a)d[f]=c[a];for(a=0;a<h;++f,++a)d[f]=c[a]}this.buffer=d;this.head=0;this.tail=this.length};return c})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/scheduler",["require","./Queue"],function(c){function b(b){this._enqueue=b;this._handlerQueue=new a(15);var c=this;this.drainQueue=function(){c._drainQueue()}}var a=c("./Queue");b.prototype.enqueue=function(a){1===this._handlerQueue.push(a)&&this._enqueue(this.drainQueue)};b.prototype._drainQueue=function(){for(var a=this._handlerQueue;0<a.length;)a.shift().run()};return b})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
(function(d){d("qowtRoot/third_party/when/lib/async",["require"],function(c){var b;return"undefined"!==typeof process&&null!==process&&"function"===typeof process.nextTick?function(a){process.nextTick(a)}:(b="function"===typeof MutationObserver&&MutationObserver||"function"===typeof WebKitMutationObserver&&WebKitMutationObserver)?function(a,b){var c,d=a.createElement("div");(new b(function(){var a=c;c=void 0;a()})).observe(d,{attributes:!0});return function(a){c=a;d.setAttribute("class","x")}}(document,
b):function(a){var b=setTimeout;return function(a){b(a,0)}}(c)})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});(function(d){d("qowtRoot/third_party/when/lib/Promise",["require","./makePromise","./scheduler","./async"],function(c){var b=c("./makePromise"),a=c("./scheduler");c=c("./async");return b({scheduler:new a(c),monitor:"undefined"!==typeof console?console:void 0})})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
(function(d){d("qowtRoot/third_party/when/when","require ./lib/timer ./lib/timed ./lib/array ./lib/flow ./lib/inspect ./lib/iterate ./lib/progress ./lib/with ./lib/Promise".split(" "),function(c){function b(a,b,c,d){var e=q(a);return 2>arguments.length?e:e.then(b,c,d)}function a(a){return function(){return e(a,this,p.call(arguments))}}function d(a){return e(a,this,p.call(arguments,1))}function e(a,b,c){return g.all(c).then(function(c){return a.apply(b,c)})}function f(){function a(b){d._handler.resolve(b)}
function b(a){d._handler.reject(a)}function c(a){d._handler.notify(a)}var d=g._defer();this.promise=d;this.resolve=a;this.reject=b;this.notify=c;this.resolver={resolve:a,reject:b,notify:c}}var h=c("./lib/timer"),l=c("./lib/timed"),k=c("./lib/array"),t=c("./lib/flow"),n=c("./lib/inspect"),x=c("./lib/iterate"),z=c("./lib/progress"),u=c("./lib/with"),g=c("./lib/Promise"),g=[k,t,x,z,n,u].reduceRight(function(a,b){return b(a)},l(h.set,h.clear,g)),q=g.resolve,p=Array.prototype.slice;b.promise=function(a){return new g(a)};
b.resolve=g.resolve;b.reject=g.reject;b.lift=a;b["try"]=d;b.attempt=d;b.iterate=g.iterate;b.unfold=g.unfold;b.join=function(){return g.all(arguments)};b.all=function(a){return b(a,g.all)};b.settle=function(a){return b(a,g.settle)};b.any=a(g.any);b.some=a(g.some);b.map=function(a,c){return b(a,function(a){return g.map(a,c)})};b.reduce=function(a,c){var d=p.call(arguments,1);return b(a,function(a){d.unshift(a);return g.reduce.apply(g,d)})};b.reduceRight=function(a,c){var d=p.call(arguments,1);return b(a,
function(a){d.unshift(a);return g.reduceRight.apply(g,d)})};b.isPromiseLike=function(a){return a&&"function"===typeof a.then};b.Promise=g;b.defer=function(){return new f};return b})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
define("qowtRoot/utils/promiseUtils",["qowtRoot/utils/typeUtils","qowtRoot/third_party/when/when"],function(d,c){var b={cast:function(a){return a instanceof Promise?a:Promise.resolve(a)},delay:function(a,b){a=a||0;return new Promise(function(c){setTimeout(c.bind(void 0,b),a)})},delayThenReject:function(a,b){a=a||0;return new Promise(function(c,d){setTimeout(d.bind(c,b),a)})},throwAndEscapeChain:function(a){a instanceof Error||(console.error("throwAndEscapeChain wrapping value in new Error: ",a),a=
Error(a));c.reject(a).done();throw a;},pipeline:function(a){function c(){for(var f=Array.prototype.slice.call(arguments,0);0<a.length;){var l=a.shift();if(d.isPromiseLike(l))return b.cast(l).then(function(b){a.unshift(b);return c.apply(e,f)});d.checkArgTypes("PromiseUtils.pipeline",{task:[l,"function"]});l=l.apply(e,f);if(d.isPromiseLike(l))return b.cast(l).then(function(a){return c(a)});f=[l]}return f[0]}var e=this,f=Array.prototype.slice.call(arguments,0);if(f.some(d.isPromiseLike))return Promise.all(f).then(function(a){return b.pipeline.apply(e,
a)});d.checkArgTypes("PromiseUtils.pipeline",{tasks:[a,"list"]});a=a.slice(0);return c.apply(e,f.slice(1))},finally:function(a,c){function d(){return b.cast(c()).then(function(){return a})}return b.cast(a).then(d,d)},waitForNextMacroTurn:function(a){return new Promise(function(b){window.setTimeout(b.bind(null,a),0)})}};return b});
define("utils/analytics/googleAnalytics",["qowtRoot/features/utils","qowtRoot/utils/promiseUtils"],function(d,c){function b(b,c){var e;void 0!==g?e=g?Promise.resolve():Promise.reject(Error("ga permission cached (not permitted)")):(window.analytics&&chrome&&chrome.metricsPrivate&&chrome.metricsPrivate.getIsCrashReportingEnabled&&(!d.isDebug()||void 0!==window.__gaMock)?e=Promise.resolve():(console.warn("GA not supported on this platform"),e=Promise.reject(Error("GA not supported on this platform"))),
e=e.then(a).catch(f));return e.then(h).then(b.bind(null,c)).catch(function(){})}function a(){var a=Error("Crash reporting setting timed out");return Promise.race([r(),c.delayThenReject(1E3,a)]).then(e)}function r(){return new Promise(function(a){chrome.metricsPrivate.getIsCrashReportingEnabled(a)})}function e(a){return new Promise(function(b,c){q=window.analytics.getService(z);q.getConfig().addCallback(function(d){d.setTrackingPermitted(a);(g=a)?b():(console.warn("Crash reporting not allowed"),c())})})}
function f(){g=!1;return Promise.reject()}function h(){void 0===p&&l("QO");return Promise.resolve()}function l(a){p&&p.sendAppView(a);p=q.getTracker(x[a]);v&&p.set(window.analytics.Parameters.SESSION_GROUP,v);p.forceSessionStart();return Promise.resolve()}function k(a){u!==a&&(u=a,p.sendAppView(a));return Promise.resolve()}function t(a){p.sendException(a.msg,a.fatal);return Promise.resolve()}function n(a){p.sendEvent(a.category,a.action,a.label,a.value);return Promise.resolve()}var x={word:"UA-44583639-1",
sheet:"UA-44583639-2",point:"UA-44583639-3",QO:"UA-44583639-4"},z="Quickoffice",u,g,q,p,v;return{setSessionGroup:function(a){v=a},setTracker:function(a){return b(l,a)},sendState:function(a){return b(k,a)},sendException:function(a){return b(t,a)},sendEvent:function(a){return b(n,a)},reset:function(){p=q=g=u=void 0}}});
define("qowtRoot/utils/i18n",["qowtRoot/utils/typeUtils","utils/analytics/googleAnalytics"],function(d,c){var b={getMessage:function(a,c){var e="????";if(!chrome||!chrome.i18n)return a;d.isString(a)?(e=chrome.i18n.getMessage(a,c),e||(e=a,b.logError_("Missing translation",a))):b.logError_("Invalid string translation Id",a);return e},logError_:function(a,b){console.error(a+" "+b);c.sendException({msg:a,fatal:!1})}};return b});
require(["third_party/domready/domReady!"],function(){require(["qowtRoot/utils/i18n"],function(d){document.getElementById("messageBody").innerHTML=d.getMessage("extension_popup_message_body")})});define("mainPopup",function(){});
